
import React, { useState, useEffect } from 'react';
import { X, Github, ExternalLink, AlertCircle, Rocket, CheckCircle2 } from 'lucide-react';
import { Button } from './Button';
import { Project } from '../types';
import { createGitHubRepo, pushToGitHubRepo } from '../services/githubService';

interface DeployModalProps {
  isOpen: boolean;
  onClose: () => void;
  project: Project;
  onUpdateProject: (project: Project) => void;
}

export const DeployModal: React.FC<DeployModalProps> = ({ isOpen, onClose, project, onUpdateProject }) => {
  const [token, setToken] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [repoName, setRepoName] = useState('');
  const [step, setStep] = useState<'token' | 'create' | 'deploy'>('token');

  // Load token from local storage on mount
  useEffect(() => {
    const savedToken = localStorage.getItem('github_pat');
    if (savedToken) {
        setToken(savedToken);
        setStep('create');
    }
    // Pre-fill repo name from project name
    const sanitizedName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
    setRepoName(sanitizedName || 'my-ai-app');
  }, [isOpen, project.name]);

  // If project already has a repo, jump to deploy step
  useEffect(() => {
      if (project.githubRepo && project.githubOwner) {
          setStep('deploy');
      }
  }, [project.githubRepo, project.githubOwner]);

  if (!isOpen) return null;

  const handleSaveToken = () => {
    if (!token.trim()) return;
    localStorage.setItem('github_pat', token.trim());
    setStep('create');
  };

  const handleCreateRepo = async () => {
    if (!repoName.trim()) {
        setError("Repository name is required");
        return;
    }
    
    setIsLoading(true);
    setError(null);

    try {
        // 1. Create Repo
        const repoData = await createGitHubRepo(token, repoName, project.description || "Generated by Supa App Builder");
        
        // 2. Push initial code
        await pushToGitHubRepo(token, repoData.owner, repoData.repo, project.files, "Initial commit from Supa App Builder");

        // 3. Update Project
        onUpdateProject({
            ...project,
            githubOwner: repoData.owner,
            githubRepo: repoData.repo
        });

        setStep('deploy');

    } catch (e: any) {
        console.error(e);
        setError(e.message || "Failed to create repository");
    } finally {
        setIsLoading(false);
    }
  };

  const getVercelDeployUrl = () => {
      if (!project.githubOwner || !project.githubRepo) return '';
      const repoUrl = `https://github.com/${project.githubOwner}/${project.githubRepo}`;
      // Vercel deploy link pattern
      return `https://vercel.com/new/clone?repository-url=${encodeURIComponent(repoUrl)}&project-name=${project.githubRepo}`;
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="w-full max-w-md bg-surface border border-border rounded-xl shadow-2xl animate-in fade-in zoom-in-95 duration-200">
        
        <div className="flex items-center justify-between p-4 border-b border-border">
          <div className="flex items-center gap-2">
            <Rocket className="h-5 w-5 text-white" />
            <h2 className="text-lg font-semibold text-white">Deploy App</h2>
          </div>
          <button onClick={onClose} className="text-zinc-400 hover:text-white transition-colors">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="p-6">
            {step === 'token' && (
                <div className="space-y-4">
                     <div className="text-center mb-6">
                        <div className="w-12 h-12 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-3">
                            <Github className="h-6 w-6 text-white" />
                        </div>
                        <h3 className="text-white font-medium">Connect GitHub</h3>
                        <p className="text-sm text-zinc-400 mt-1">Enter your Personal Access Token to create a repository.</p>
                     </div>
                     
                     <div>
                        <label className="text-xs font-medium text-zinc-300">GitHub Personal Access Token</label>
                        <input 
                            type="password" 
                            value={token}
                            onChange={(e) => setToken(e.target.value)}
                            className="w-full mt-1 bg-black/20 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-1 focus:ring-primary placeholder:text-zinc-600"
                            placeholder="ghp_..."
                        />
                        <p className="text-[10px] text-zinc-500 mt-1">
                            Requires 'repo' scope. <a href="https://github.com/settings/tokens" target="_blank" className="text-primary hover:underline">Generate Token</a>
                        </p>
                     </div>

                     <div className="flex justify-end pt-2">
                        <Button onClick={handleSaveToken} disabled={!token}>
                            Next
                        </Button>
                     </div>
                </div>
            )}

            {step === 'create' && (
                <div className="space-y-4">
                    <h3 className="text-white font-medium">Create Repository</h3>
                    <p className="text-sm text-zinc-400">
                        We will create a public GitHub repository and push your code to it.
                    </p>

                    <div>
                        <label className="text-xs font-medium text-zinc-300">Repository Name</label>
                        <input 
                            type="text" 
                            value={repoName}
                            onChange={(e) => setRepoName(e.target.value)}
                            className="w-full mt-1 bg-black/20 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-1 focus:ring-primary placeholder:text-zinc-600"
                        />
                    </div>

                    {error && (
                        <div className="flex items-start gap-2 p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-sm">
                        <AlertCircle className="h-4 w-4 mt-0.5 flex-none" />
                        <span>{error}</span>
                        </div>
                    )}

                    <div className="flex justify-end gap-3 pt-2">
                        <Button variant="secondary" onClick={() => setStep('token')}>Back</Button>
                        <Button onClick={handleCreateRepo} isLoading={isLoading}>
                            Create & Push
                        </Button>
                    </div>
                </div>
            )}

            {step === 'deploy' && (
                <div className="space-y-6 text-center">
                    <div className="w-16 h-16 bg-emerald-500/10 rounded-full flex items-center justify-center mx-auto">
                        <CheckCircle2 className="h-8 w-8 text-emerald-400" />
                    </div>
                    
                    <div>
                        <h3 className="text-xl font-bold text-white">Code Pushed!</h3>
                        <p className="text-zinc-400 text-sm mt-2">
                            Your code is now on GitHub. Click below to deploy it live with Vercel.
                        </p>
                    </div>

                    <div className="p-4 bg-surface border border-border rounded-lg text-left flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <Github className="h-5 w-5 text-white" />
                            <div>
                                <div className="text-sm font-medium text-white">{project.githubOwner}/{project.githubRepo}</div>
                                <div className="text-xs text-zinc-500">Main branch</div>
                            </div>
                        </div>
                        <a 
                            href={`https://github.com/${project.githubOwner}/${project.githubRepo}`}
                            target="_blank"
                            rel="noreferrer"
                            className="text-xs text-zinc-400 hover:text-white"
                        >
                            View Repo
                        </a>
                    </div>

                    <a 
                        href={getVercelDeployUrl()}
                        target="_blank"
                        rel="noreferrer"
                        className="flex items-center justify-center w-full gap-2 bg-white text-black font-bold py-3 px-4 rounded-lg hover:bg-zinc-200 transition-colors"
                    >
                        <svg className="h-4 w-4" viewBox="0 0 1155 1000" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M577.344 0L1154.69 1000H0L577.344 0Z" fill="black"/>
                        </svg>
                        Deploy to Vercel
                    </a>
                    
                    <Button variant="ghost" onClick={onClose} className="w-full">
                        Done
                    </Button>
                </div>
            )}
        </div>
      </div>
    </div>
  );
};
